version: '3.8'
services:
    nuxt:
        build: .
        image: nuxt
        volumes:
            - ./nuxt:/workspace
        ports:
            - target: 10000
              published: 3000
              mode: host
        command: 'nuxt --hostname 0.0.0.0 --port 3000'
# docker-compose run nuxt create-nuxt-app
